Homework
YuraMitriakhin/multithreading-01 pull request #1
Opened 2021-02-22 13:32 UTC by YuraMitriakhin

2021-02-22 14:02 UTC, Vedroid approved these changes

2021-02-22 16:05 UTC, Sofasmile requested changes

2021-02-22 16:05 UTC, Sofasmile commented on src/main/java/com/gmail/yuramitryahin/Counter.java
> +    public void increment() {
```suggestion
    public int increment() {
```

2021-02-22 16:05 UTC, Sofasmile commented on src/main/java/com/gmail/yuramitryahin/RunnableImpl.java
> +            counter.increment();
```suggestion
            int result = counter.increment();
```

2021-02-22 16:05 UTC, Sofasmile commented on src/main/java/com/gmail/yuramitryahin/RunnableImpl.java
> +            logger.info(Thread.currentThread().getName() + ":" + counter.getCount());
```suggestion
            logger.info(Thread.currentThread().getName() + ":" + result);
```

2021-02-23 07:57 UTC, Sofasmile approved these changes

2021-02-23 12:29 UTC, merged